# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Alrubaye-py-flask

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_187109ab16c14e7981ec73c10ff375d5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_77757839fb4b4a139a163e079cced60c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_187109ab16c14e7981ec73c10ff375d5 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Alrubaye-py-flask'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3221e48dcee54a5a8f22cc72f0ad7cdb }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_187109ab16c14e7981ec73c10ff375d5 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'